### ISSUE TITLE
Number of chromosmes if using two pseudo haplotypes from hifiasm

### ISSUE THREAD

**Issue by chregu1971** [zengxiaofei/HapHiC#1]
Hi,
If I combine hap1 and hap2 from hifiasm for scaffolding. Do I have to set the number of chromosomes to the haploid or diploid number?
Best regards,
Christian

**Comment by zengxiaofei** [comment]
> Hi, If I combine hap1 and hap2 from hifiasm for scaffolding. Do I have to set the number of chromosomes to the haploid or diploid number? Best regards, Christian

Hi Christian,

You should set the number of chromosomes `nchrs` to the diploid number.

If you are uncertain about the exact number of chromosomes, you can also try [the quick view mode](https://github.com/zengxiaofei/haphic#quick_view).

It is worth noting that scaffolding multiple haplotypes with extremely low heterozygosity, such as human genomes, remains a challenge for all existing scaffolders. This is because that most of the Hi-C reads mapping to these haplotypes will be filtered out with a loose threshold of MAPQ >= 1. In these cases, you may still need to scaffold each haplotype separately.

Best wishes,
Xiaofei
