### ISSUE TITLE
Overrepresented / duplicated contigs as input

### ISSUE THREAD

**Issue by jolbi** [zengxiaofei/HapHiC#11]
Hi, 

Thank you for this impressive tool, I am very excited to try it!

I am not sure about which set of contigs to choose for input. If I understand correctly HapHic takes care of the collapsed contigs and chimeric ones. What happens if I feed it with overrepresented sequences like an under-purged set of contigs?
Here is a merqury plot of the input set I will try:
![image](https://github.com/zengxiaofei/HapHiC/assets/63711717/b741ede3-64ab-4d77-a33f-dab00c8bd0e6)
I used hifiasm with HiC phasing to get four "haplotypes". Plot represents a merged set of all 4 hap sets.

With purging I always lose a lot of haplo- and diplotigs, which will be a problem in the scaffolding stage. Do you think the above set is siutable for HapHic?

**Comment by zengxiaofei** [comment]
Hi @jolbi,

> What happens if I feed it with overrepresented sequences like an under-purged set of contigs?

It depends on the heterozygosity and the distribution of variations along the genome. The Hi-C reads mapped to identical/nearly identical contigs will be filtered out by the criterion `MAPQ >= 1`. If there are too many such kind of contigs, the anchoring rate will be significantly reduced.

> Do you think the above set is siutable for HapHiC?

As a first step, you could try scaffolding the merged set of four haplotypes. Since you mentioned that the genome assembly was conducted using hifiasm with Hi-C phasing, you may benefit from utilizing the phasing information available in the GFA files when running HapHiC ([more details](https://github.com/zengxiaofei/HapHiC#hifiasm)). If the anchoring rate is too low, or the scaffolds are difficult to manually curated in Juicebox due to inadequate Hi-C links, you could scaffold each haplotype individually.

Best regards,
Xiaofei
