### ISSUE TITLE
the applicability of haphic

### ISSUE THREAD

**Issue by ChuanzhengWei** [zengxiaofei/HapHiC#45]
Dear Xiaofei,

I would like to seek your advice regarding the applicability of haphic. I am currently planning to assemble the genome of a self-pollinating plant with very low heterozygosity, similar in size to the rice genome. In your experience, would you recommend using haphic for chromosome-level assembly in this case?

Additionally, if the assembly results from hifiasm are already quite close to a complete genome (around 50%-60% of the chromosomes), would you suggest first breaking the contigs with allhic before using haphic?

Thank you for your time and guidance.

Best regards,

**Comment by zengxiaofei** [comment]
> In your experience, would you recommend using haphic for chromosome-level assembly in this case?

I usually do not consider heterozygosity as a direct reference metric because different methods and choices of homologous peaks can lead to vastly different results in heterozygosity calculation. Another important factor influencing the scaffolding of haplotype-resolved assemblies is the uniform distribution of heterozygous sites. For instance, although the heterozygosity of the human genome HG002 is relatively low, HapHiC still performs well (refer to **Supplementary Figs. 53** and **54** in [our paper](https://doi.org/10.1038/s41477-024-01755-3)). Therefore, I suggest starting by using HapHiC to scaffold haplotypes simultaneously. If you find that the filtering with MAPQ>=0 results in insufficient Hi-C links or if they are unevenly distributed along the assembly, then consider using HapHiC to scaffold each haplotype (hap*.p_ctg) separately. After that verify the results through mapping all Hi-C read to the combined chromosome-level haplotypes, filtering multiple mappings with MAPQ>=1, and visualizing it using Juicebox or `haphic plot`. 

> Additionally, if the assembly results from hifiasm are already quite close to a complete genome (around 50%-60% of the chromosomes), would you suggest first breaking the contigs with allhic before using haphic?

I do not recommend performing assembly correction before scaffolding for hifiasm assemblies since hifiasm usually does not produce many misjoined (chimeric) contigs. My preference is to manage these contigs in Juicebox to ensure the max length of the contig. In addition, the assembly correction function of ALLHiC is too aggressive, as shown in **Supplementary Figs. 10** and **11**, and **Fig. 5** in [our paper](https://doi.org/10.1038/s41477-024-01755-3). Thus, I do not recommend using it in any situation. If you need to perform assembly correction in HapHiC, please use the `--correct_nrounds` parameter.
