### ISSUE TITLE
Haphic plot question

### ISSUE THREAD

**Issue by majssssa** [zengxiaofei/HapHiC#48]
Hi, 

When I ran "/path/to/HapHiC/haphic plot out_JBAT.FINAL.agp HiC.filtered.bam", a very Hi-C contact maps appeared. Oddly, this is not the case in Juicebox.
[contact_map.pdf](https://github.com/user-attachments/files/16632032/contact_map.pdf)

**Comment by zengxiaofei** [comment]
In some cases, `haphic plot` may not able to get a suitable color range automatically due to a strong background of inter-scaffold Hi-C signals. In such scenarios, please set the color range manually using the `--manual_vmax` parameter (e.g., your may try 0.00001 or higher in your case).

**Comment by zengxiaofei** [comment]
Note: If you only change the `--manual_vmax` parameter, you do not need to rerun `haphic plot` using the BAM file. Instead, you can just use the `contact_matrix.pkl` file instead, which is super fast.

**Comment by majssssa** [comment]
Thank you. That problem has been solved.
Another small problem is that after modification by Juicebox, there will be an extra Scaffold. Can we keep the extra scaffold deleted when using Haplot?
The Scaffold_
[contact_map.pdf](https://github.com/user-attachments/files/16632585/contact_map.pdf)
19 in the figure below

**Comment by zengxiaofei** [comment]
We recommend not to link these unanchored contigs into a scaffold (chrUn) as you have done, because it is not a true scaffold and could be misleading. Instead, we prefer to separately list these contigs after the true chromosomes (chr1-18). After that, you can easily exclude these short unanchored sequences from the contact map using the `--min_len` parameter.

Currently, `haphic plot` does not support the removal of specific sequences by modifying the AGP file, which is intentional to prevent users from inputting mismatched AGP files and BAM files. If you still decide to present the unanchored sequences using the chrUN, you need to filter out scaffold_19 in both the AGP file and the BAM file.

I plan to add a feature that allows users to manually specify which sequences will be included in the contact map. However, this will take some time as I am quite busy this month.

**Comment by majssssa** [comment]
Thank you for your reply. My problem has been solved and I have made a heat map that I am satisfied with.

**Comment by zengxiaofei** [comment]
I have added a new parameter `--specified_scaffolds` in haphic plot in the latest [commit](https://github.com/zengxiaofei/HapHiC/commit/ecab25640df90c523812cec6da7dd7a5502523b1) . You can specify the scaffolds to visualize by using something like: `--specified_scaffolds "group1,group2,group3,group4"`
