### ISSUE TITLE
How to set nchr in human male?

### ISSUE THREAD

**Issue by DayTimeMouse** [zengxiaofei/HapHiC#53]
Hi [zengxiaofei](https://github.com/zengxiaofei),

When I assembly human male genome(primary genome), I do not sure how to set nchr parameter. If I want to assembly chr1,chr2,...chr22,chrX,chrY, should I need to set nchr to 24？

Another situation, if I set nchr to 23, this means chr1,chr2,...chr22,chrX?

Best wishes.

**Comment by zengxiaofei** [comment]
>  If I want to assembly chr1,chr2,...chr22,chrX,chrY, should I need to set nchr to 24?

Yes.

> Another situation, if I set nchr to 23, this means chr1,chr2,...chr22,chrX?

No. The sequences contained in your final scaffolds depend on the sequences you assembled and input into HapHiC. If you have already assembled all primary sequences of a human male genome, there should be sequences from chrY in your assembly. But when you set the `nchrs` parameter to `23`, two chromosomes will be grouped together.

**Comment by DayTimeMouse** [comment]
After I set nchr to 24, compared to nchr=23, HapHiC splits one of the clusters into two clusters, which also have strong contact between this two clusters. The pictures are below:
nchr=24
![image](https://github.com/user-attachments/assets/4a494db6-da33-49df-942b-a026c8037fe5)
nchr=23
![image](https://github.com/user-attachments/assets/e068a3a0-10e2-45ef-973b-7e65e6d3c2d0)

Is the result right?

**Comment by zengxiaofei** [comment]
I'm not sure whether these contigs should originate from one or two chromosomes. There are indeed some difficulties in assembling the Y chromosome of the human genome. You can align your scaffolds to the CHM13 T2T genome (with Y) to figure this out.

**Comment by DayTimeMouse** [comment]
Hi there,
I used HapHiC refsort to generate `scaffolds.refsort.agp`, which instead of `scaffolds.raw.agp` to run bash juicebox.sh, then get out_JBAT.FINAL.fa. 
However, the paf file is compared between the Scaffold and the reference genome, and the paf is visualized in the following figure. The alignment of the Scaffold to the reference genome is not in the same direction, not on the same diagonal. How can this be resolved?
![scaffold2ref paf](https://github.com/user-attachments/assets/4d9dd53c-56cc-48f9-8941-a797fb4180a8)

**Comment by zengxiaofei** [comment]
These scaffolds that appear not in the same direction are actually incorrectly ordered and oriented by HapHiC. Please note that `haphic refsort` only changes the overall ordering and orientation of entire scaffolds, it does not alter your scaffolds. **This function is NOT reference-base scaffolding!!**. Therefore, this problem still exists after running `haphic refsort`. Although we have emphasized it in the documentation, many users still misunderstand it:

> Please note that this function will NOT alter your scaffolds, it only changes the way of presentation through overall ordering and orientation of the entire scaffolds.

Such ordering and orientation errors are very common in Hi-C scaffolding due to the relatively low contact frequency between the two arms of chromosomes in human genomes. There are also other difficulties in scaffolding human genomes, as well as the genomes of many other mammals. For example, the physical distance does not correlate well with the contact intensity, as shown in panel A of the figure below:

![human_hic](https://github.com/user-attachments/assets/8cad7f7b-e565-4f68-931a-635c33271552)
(Ghurye, J. et al. Integrating Hi-C links with assembly graphs for chromosome-scale assembly, bioRxiv, 2018)

Too solve this problem, you can manually adjust your assembly in Juicebox.

Another problem: as you set the `nchrs` to 23, based on the dotplot you provided, chrX and chrY are grouped together.

**Comment by DayTimeMouse** [comment]
Thanks a lot!
