### ISSUE TITLE
Inquiry about Using  Additional Tools for Chromosome Reordering after HapHiC  analysis

### ISSUE THREAD

**Issue by ucsfpan** [zengxiaofei/HapHiC#80]
Hi Xiaofei,
Thanks so much for the great tools! The flexibility and efficiency of HapHiC have been incredibly impressive and have significantly streamlined my workflow. 
I have a question regarding the refsort function. As per my understanding, HapHiC has introduced a separate command, haphic refsort, in version 1.0.4 to order and orient whole scaffolds according to a reference genome.
Because this function is NOT reference-based scaffolding and will NOT alter your scaffolds; it only changes the way of presentation through overall ordering and orientation of the entire scaffolds. Given this, if I want to reorder the scaffolds according to chromosomes and perform JCVI alignment, which software can be used after HapHiC? Would "RagTag -scaffold" be a suitable option using 04.build/scaffolds.fa?
I would greatly appreciate your guidance on this matter. Thank you for your time and assistance!

**Comment by zengxiaofei** [comment]
By default, HapHiC outputs scaffolds (typically chromosome-level or nearly chromosome-level) with an ordering sorted by scaffold length and a random orientation. If you only want to order and orient your entire scaffolds based on a reference genome, please use `haphic refsort`. The ordered and oriented scaffolds are still fully supported by Hi-C data. RagTag (`ragtag scaffold`) can also generate similar results, but it may join multiple scaffolds into a single one according to its principle, resulting in the inclusion of evidence from the reference genome in the scaffolds, not just Hi-C data.

**Comment by ucsfpan** [comment]
Thanks so much for your help. Could you please advise on how I can determine the chromosomal assignment for each contig in my dataset? (Which contig belong to which chromosome) My command line is :" minimap2 -x asm20 T2T_CHM13_V2/hs1.2bit.fa ./COLO829.asm.hifiasm.fa --secondary=no -t 28 -o asm_to_ref.paf
$HapHiC/haphic refsort 04.build/scaffolds.raw.agp asm_to_ref.paf > scaffolds.refsort.agp
$HapHiC/haphic refsort 04.build/scaffolds.raw.agp asm_to_ref.paf --ref_order chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY > scaffolds.refsort.chr.agp " 
I have attached a sample of my output for your reference.
[scaffolds.refsort.zip](https://github.com/user-attachments/files/17358976/scaffolds.refsort.zip)

**Comment by zengxiaofei** [comment]
> Could you please advise on how I can determine the chromosomal assignment for each contig in my dataset?

This information should have been included in the logs, something like:

```
chr1, group3 +/-
```

**Comment by ucsfpan** [comment]
Truly appreciate your guidance. I'm wondering if I replace "group3" with "chr1" in the "scaffolds.refsort.agp" file would be sufficient. Would that be correct?

**Comment by zengxiaofei** [comment]
It depends. Current scaffolding tools cannot guarantee perfect results, so manual curation in Juicebox is often necessary. The output of HapHiC (scaffolds.raw.agp) may contain some chromosomal misassignments. It would be better if you manually adjust the results in Juicebox before running haphic refsort. Another issue is when the assembly contains multiple haplotypes; one chromosome in the reference genome can have more than one corresponding scaffold, so these scaffolds should be renamed to something like "chr1_1," "chr1_2," etc.

**Comment by ucsfpan** [comment]
Thank you so much for your insightful advice. I will try to use manual curation to adjust the results. Thanks!

**Comment by Isoris** [comment]
I would like to ask, if we give a haplotype resolved assembly for instance 

cat hap1.fa hap2.fa > asm.fa 

and then we get the final genome out_JBAT.FINAL.fa after post review in JBAT of the asm.fa using the scaffold.refsort.agp.

The contigs are now named 

Scaffold_1
Scaffold_2
Scaffold_3

First question is, can you change to name from 01 02 03 04 instead of 1 2 3 4 because in bash it will order from 1 10 11 12 .. 2 20 21 22 ..  and its a bit messy in the command line ?

The second question is how to get the phasing information again, for instance for very small contigs that showed haplotype switches patterns (the hic pattern was strong with the opposite chromosome, then we get this in the final agp:

`BWA_MEM_5SP_HiC/04.build> cat out_JBAT.FINAL.agp | cut -f1,2,6
scaffold_1      1       HiC_scaffold_68_hap1_1_212635
scaffold_1      212636  100
scaffold_1      212736  HiC_scaffold_21_hap2_9085232_24725964
scaffold_1      15853469        100
scaffold_1      15853569        HiC_scaffold_21_hap2_3501833_9085231
scaffold_1      21436968        100
scaffold_1      21437068        HiC_scaffold_21_hap2_1848886_3501832
scaffold_1      23090015        100
scaffold_1      23090115        HiC_scaffold_258_hap1_1_86110
scaffold_1      23176225        100
scaffold_1      23176325        HiC_scaffold_21_hap2_724403_1848885
scaffold_1      24300808        100
scaffold_1      24300908        HiC_scaffold_221_hap1.1_1_51883
scaffold_1      24352791        100
scaffold_1      24352891        HiC_scaffold_21_hap2_1_724402
scaffold_2      1       HiC_scaffold_117_hap1_1_148072
scaffold_2      148073  100
scaffold_2      148173  HiC_scaffold_23_hap1_6797813_24363869
scaffold_2      17714230        100
scaffold_2      17714330        HiC_scaffold_23_hap1_1_6797812
scaffold_2      24512142        100
scaffold_2      24512242        HiC_scaffold_218_hap1_1_97978
scaffold_2      24610220        100
scaffold_2      24610320        HiC_scaffold_489_hap2_1_50833
scaffold_3      1       HiC_scaffold_1_hap2_582962_43028588
scaffold_3      9387657 100
scaffold_3      9387757 HiC_scaffold_126_hap1_1_145795
scaffold_3      9533552 100
scaffold_3      9533652 HiC_scaffold_108_hap1_1_158383
scaffold_3      9692035 100`

is it possible to give 2 fasta files to HapHic instead of 1 ? so we can recover the belongings of namings at the end ?

**Comment by zengxiaofei** [comment]
The first question:

I currently do not have a plan to change the scaffold ID because:

1. Scaffolds are similar to chromosomes; the chromosome IDs of human genomes are named chr1~22, chrX, and chrY.
2. If I were to change them to chr01, chr02, when the number of scaffolds exceeds one hundred, I would need to change them to chr001, chr002 to keep them correctly ordered in the command line, which feels a little strange.
3. Some concerns about backward compatibility.

The second question:

You can find the contig IDs in the final AGP file. If you did not rename them, they can reflect the haplotype to which they were assigned by hifiasm. The phasing results of hifiasm may not always be correct. By default, HapHiC may cluster contigs from different haplotypes into a single group (scaffold). Of course, HapHiC is not always correct either. If you just want to ensure that contigs from different haplotypes are never clustered together, you can use the parameter `--gfa *.hap1.p_ctg.gfa,*.hap2.p_ctg.gfa` (for more information, please refer to: https://github.com/zengxiaofei/HapHiC#hifiasm)

**Comment by Isoris** [comment]
Hello thank you for the quick answers it is informative and helpful.

I have another question, so if the HiC pattern intra contig ( inside of a
green square) show like a strong interraction with the opposite haplotype
it means that this little part is a haplotype switch error right ? When at
MAPQ1.

So it makes sense to cut the contig with the scissors and to move it to the
desired location in the opposite haplotype contig in Juicebox. So nothing
special here. But then when we save the scaffolds it will show the changes
in the AGP file, as you explained.

So my question is, I can simply rename the scaffolds by myself as you said,
right? Because my starting contigs are from hifiasm but I already polished
them and went in JBAT and so on before thats why the names of the contigs
are different than the hifiasm GFAs so I cannot use the GFA files. Because
I believe my assembly now is much better than hifiasm.

I went from 8,000 contigs in hifiasm, QV 31 to QV 51 and 500 gaps.. more or
less. But there was still some regional errors thats why I run HapHiC for
the last and fourth round of JBAT instead of 3DDNA. But I also noticed that
at MAPQ1  HapHiC basically removed my telomeres ( it was kind of expected,
maybe if I choose no contig correction and MAPQ0 it would preserve it? )

Or maybe I should process each Haplotype separately in HapHiC?

It's like while HapHiC improved the chromosome arms it also damaged the
assembly. So I need to find a way to fill gaps to  bridge assembly gaps in
HapHiC jbat Final fasta and use the long contigs to scaffold my First
assembly or idk..

All of this is complicated.. I don't understand why in JBAT the chromosomes
looked linear and great and after HapHiC it looked like it needed a lot of
manual curation? So you think that the contig correction could have damaged
the assembly ? Or that the JBAT from the round 3 that looked correct on
both separate haplotypes was actually  wrong because it didn't use the -5SP?

**Comment by zengxiaofei** [comment]
So, you used the results of 3D-DNA for HapHiC scaffolding, right? I'm not sure how you did this. For example, did you use the output scaffolds of 3D-DNA as the input asm.fa for HapHiC? If the 3D-DNA scaffolds are already at the chromosome level and look good in Juicebox, there is no need to use HapHiC. Just adjusting them in Juicebox is okay. If the 3D-DNA scaffolds are very short, HapHiC may be helpful (equivalent to considering these scaffolds as longer contigs). However, if the 3D-DNA has many scaffolding errors, HapHiC may not be able to correct all these errors using the assembly correction function. In this case, it would be better if you use HapHiC to perform scaffolding from the original contigs. The contig IDs in the sixth column of the *.Final.agp should be consistent with the sequence IDs of input asm.fa. I don't know how you renamed these sequence IDs, so I don't know how to map them to the original hifiasm contig IDs.

> But I also noticed that at MAPQ1 HapHiC basically removed my telomeres ( it was kind of expected, maybe if I choose no contig correction and MAPQ0 it would preserve it? )

If these telomeres are not anchored to any groups (scaffolds), it could be due to MAPQ>=1 filtering. The contigs containing these sequences may be very similar to some other contigs, resulting in multiple alignments during Hi-C read mapping, and these alignments are designated a MAPQ of 0. Actually, the 3D-DNA pipeline also uses the MAPQ>=1 criterion, however, the Hi-C read mapping pipeline (Juicer pipeline) is somewhat different from the mapping and filtering approach we recommended. We find that the Juicer pipeline will retain more incorrectly mapped reads. So these contigs may have Hi-C signals in the .hic files generated by 3D-DNA but cannot be seen in the .hic file generated by HapHiC. You can try different filtering criteria in the visualization steps, with an awareness of possible mapping errors. In addition, the correct placements of these telomeres may also be retrieved based on the assembly graph in the GFA file if contig IDs are consistent.

> Or maybe I should process each Haplotype separately in HapHiC?

If Hi-C signals are still strong enough after MAPQ filtering, we would recommend scaffolding two haplotypes simultaneously. Scaffolding each haplotype separately will ignore possible phasing errors in the upstream analysis or the inherent SVs between haplotypes. However, if this is impossible, we may need to compromise.

If these answers do not fully resolve your confusion, I may need more information, such as how you specifically integrate 3D-DNA and HapHiC, and how HapHiC makes the results worse from the contact map. This way, I might be able to provide more detailed advice.

**Comment by Isoris** [comment]
Because I thought that HapHic was more precise and that it would be better
to solve the small gaps at the regional level not structural. But it seems
that yes after manual curation the automatic scaffolders wether it is
HapHiC or 3DDNA are not going to improve it.

So id I just want to have the beautiful plots, I can run take the output
from 3DDNA/ JBAT and simply run HapHiC in quickview mode right?

**Comment by Isoris** [comment]
Because at first when I did 3DDNA and the manual curation the QV was 31.
But now it's 51 so I thought that using HapHiC with the 5SP filtering
method and the increase of QV from the polishing would give me more
resolution or power to rescaffold the small contigs. But it seems more
complicated that that. Now I am trying to run it on the separate
haplotypes. It may give better results? Let's see.

**Comment by Isoris** [comment]
[contact_map.pdf](https://github.com/user-attachments/files/17449677/contact_map.pdf)

After sorting to Clarias fuscus ( a closely related species to my catfish ) ^ 

And the scaffolds looked like this: after manual review:
A:
![Screenshot 2024-10-20 103310](https://github.com/user-attachments/assets/11eee00c-44af-41f1-8e8c-a2c80d6db034)
B:
![Screenshot 2024-10-20 103303](https://github.com/user-attachments/assets/7bbd0f84-8128-4586-b9f9-6d132319d452)
C:
![Screenshot 2024-10-20 103248](https://github.com/user-attachments/assets/d4195f37-c5f4-42e7-b225-e1f693a41996)
D:
![Screenshot 2024-10-20 103220](https://github.com/user-attachments/assets/1ba44c59-43c1-4066-b3ea-e197586be169)
E:
![Screenshot 2024-10-20 103206](https://github.com/user-attachments/assets/d6be3e14-311d-4bdc-9417-af6229fb694a)
F:
![Screenshot 2024-10-20 103153](https://github.com/user-attachments/assets/17bb55fd-6a70-4572-a963-bda578455e7e)
G:
![Screenshot 2024-10-20 103144](https://github.com/user-attachments/assets/b05a0e88-b010-498c-b021-f837bbf9ed0a)
H:
![Screenshot 2024-10-20 103043](https://github.com/user-attachments/assets/b0b4637b-7d4c-4734-88e8-272aa1b9ef65)
I:
![Screenshot 2024-10-20 102956](https://github.com/user-attachments/assets/fbb893ea-4e4c-4465-ae36-dc555c540d85)
J:
![Screenshot 2024-10-20 102949](https://github.com/user-attachments/assets/d7f7218e-cb91-43db-95af-6768c44b3531) 
K:
![Screenshot 2024-10-20 102941](https://github.com/user-attachments/assets/195f6959-1a67-4294-9987-b8d28679d410)
L:
![Screenshot 2024-10-20 102841](https://github.com/user-attachments/assets/0f2609ad-61a0-4e26-b59c-34cfd5daba45)
M:
![Screenshot 2024-10-20 102744](https://github.com/user-attachments/assets/3801d49d-5be6-4ff2-9aaf-68942670f395)
N:
![Screenshot 2024-10-20 101431](https://github.com/user-attachments/assets/7f2863f3-f4c5-4797-b35a-30c11b4c01f2)
O:
![Screenshot 2024-10-20 090609](https://github.com/user-attachments/assets/653201fc-1a89-4258-b5f2-25d6419fc303)

**Comment by Isoris** [comment]
I don't understand why you say that the Juicer pipeline is different from
the 3DDNA pipeline?

The juicer pipeline just aligns reads using simple BWA but we can use the
--assemby tag to output it in a format adequate for JBAT and then we can
use the 3DDNA run assembly visualizer to filter for MAPQ1 and redo the same
for MAPQ0 and run a third time at MAPQ30 ten in JBAT we overlay the hic
maps MAPQ1 and MAPQ0 ( as control )

The MAPQ 0 will show no signal on the regions without reads mapping but
will show signals on the repeats. The MAPQ1 hic map will show the signals
only on the non repetitive regions. It would be great if HapHiC could also
output the HiC maps at MAPQ0 by default in addition to MAPQ1. Maybe post
assembly it could filter again the reads ? Or I'm not sure how to do that.

But yes the 3DDNA is a scaffolding method but in my case I used Greenhill
and then JBAT but the run assembly visualizer of 3DDNA after Juicer for
read mapping. Sorry for the oversight.

I will try HapHiC for the hybrid catfish genome then. It seems that this
genome that I work with now didn't improve much after HapHiC but I need to
verify more in detail. Because the quality values and everything that is
not structural is the same. So maybe I will just use HapHiC to make the HiC
map figures because your custom script to plot juicebox is beautiful.

However for the Hybrid catfish I am not sure wether the genome is
tetraploid or wether it is a diploid that is the sum of the two parental
species ( 27+28 chromosomes per haplotype). There is something I need to
figure out. Maybe I can try both setting as you recommended two weeks ago
with allelic links = 2 and starting from hifiasm.

There seems to be a challenge because even though we can scaffold the
chromosomes and the HiC maps look correct, it doesn't mean that the
assembly is correct in reality especially in very particular genomes.

**Comment by zengxiaofei** [comment]
There are indeed some switch errors that can be observed on the contact maps you uploaded. It seems that the green rectangles on the maps are 3D-DNA scaffolds. These errors could be introduced during the 3D-DNA scaffolding process. HapHiC is usually unable to correct them as they are too short.

My suggestion is as follows:

* Use HapHiC to scaffold raw hifiasm contigs without polishing. I think the polishing step will not have much effect on your contact map, but it will cause contig lengths to change, resulting in an exception when running HapHiC. You can polish your assembly after scaffolding. (Although the authors of nextpolish2 claim that this tool can alleviate switch errors in the human genome HG002, I have not tested it in other species yet and have not used it in constructing any haplotype-resolved assembly, sorry!)
* I notice that many regions have nearly no Hi-C signal. You can scaffold each haplotype separately (you will get two AGP files), and then validate your results in Juicebox (align Hi-C reads to the two haplotypes simultaneously, rename the first column of the two AGP files to avoid duplication, and concatenate them together).

**Comment by zengxiaofei** [comment]
> I don't understand why you say that the Juicer pipeline is different from
the 3DDNA pipeline?

Sorry, there could be some misunderstanding. I meant that the contact maps generated using the Juicer pipeline for Hi-C read mapping and filtering are different from the method we recommend [here](https://github.com/zengxiaofei/HapHiC#align-hi-c-data-to-the-assembly). The Juicer pipeline typically retains much stronger diagonally distributed Hi-C links between homologous chromosomes. We suspect these might be mapping errors, so we generally do not recommend using the Juicer pipeline for scaffolding a haplotype-resolved assembly.

**Comment by Isoris** [comment]
I am not sure but in my case I processed each haplotype separately in juicer even the BWA mapping so there was two BAM files. It may not be optimal but in species with low heterozygosity it may still work somehow? 

But yes HapHic is better but it was not really famous one year ago🤧.

**Comment by Isoris** [comment]
> There are indeed some switch errors that can be observed on the contact maps you uploaded. It seems that the green rectangles on the maps are 3D-DNA scaffolds. These errors could be introduced during the 3D-DNA scaffolding process. HapHiC is usually unable to correct them as they are too short.
> 
> My suggestion is as follows:
> 
> * Use HapHiC to scaffold raw hifiasm contigs without polishing. I think the polishing step will not have much effect on your contact map, but it will cause contig lengths to change, resulting in an exception when running HapHiC. You can polish your assembly after scaffolding. (Although the authors of nextpolish2 claim that this tool can alleviate switch errors in the human genome HG002, I have not tested it in other species yet and have not used it in constructing any haplotype-resolved assembly, sorry!)
> * I notice that many regions have nearly no Hi-C signal. You can scaffold each haplotype separately (you will get two AGP files), and then validate your results in Juicebox (align Hi-C reads to the two haplotypes simultaneously, rename the first column of the two AGP files to avoid duplication, and concatenate them together).

In Hifiasm, does the --duak-scaff option impacts the results of HapHiC?

**Comment by zengxiaofei** [comment]
> I am not sure but in my case I processed each haplotype separately in juicer even the BWA mapping so there was two BAM files. It may not be optimal but in species with low heterozygosity it may still work somehow?

Yes. Animals usually have fewer SVs between haplotypes. Many haplotype-resolved assemblies of diploids were constructed using this approach and acceptable.

> In Hifiasm, does the --dual-scaff option impacts the results of HapHiC?

Sorry, I have not used this option before because it also hypothesizes that there are no SVs between haplotypes.

**Comment by Isoris** [comment]
Ok thank you. And maybe I would kindly like to ask you the last question
for today,

Do you think that it makes sense to use Redundans or something like Purge
dups  and give the two haplotype resolves assemblies after HapHiC for
instance, to generate a primary assembly at the chromosome level?

Because for instance in my case. Each haplotype has 92% buscos and 89%
completeness

But when together the results are 95% buscos and 96% completeness.

Because on NCBI most people use Primary as reference genome but in my
opinion it would make a chimeric assembly which is wrong in reality but at
the same time if people want to do comparative genomics and use one
haplotype they may miss the 3% of genome that is haplotype specific but if
they take the chimeric primary assembly reduced for duplications after
Redundans they will get most of the genes?

What do you usually upload  on NCBI or do after HiC scaffolding a haplotype
resolved assembly with HapHic?

Thank you so much for your suggestions it really helps and gave me many
insights and a better global understanding.

Have a great day Xiaofei.

**Comment by zengxiaofei** [comment]
> Do you think that it makes sense to use Redundans or something like Purge
dups  and give the two haplotype resolves assemblies after HapHiC for
instance, to generate a primary assembly at the chromosome level?

Many studies have included both a primary assembly and a haplotype-resolved assembly. This is particularly beneficial for researchers in population genetics and gene expression regulation who may not require the haplotype information in the reference genome. Therefore, it is recommended to provide both assembly versions and allow users to choose which one to use.

> Have a great day Xiaofei.

Thank you, you too!
