### ISSUE TITLE
to combine or not to combine

### ISSUE THREAD

**Issue by AlcaArctica** [zengxiaofei/HapHiC#93]
Hi, I am new to HapHiC, but it looks like an amazing tool! I had not trouble to set it up and it is extremely well-documented and user-friendly compared to so many other bioinformatic tools out there. Our research group mainly does de novo assemblies of strange beasts and critters with hifi plus HiC data. So far my standard approach was to run hifiasm in HiC mode, then to apply purge_dups and then to run yahs on the purged assemblies and to curate in juicebox.

Now, I just have two questions in order to use HapHic appropriately. 

1) I have learned from the issues, that you do not recommend to use purge_dups. So my new approach should probably be hifiasm+hic -> haphic --> juicer. Is that correct?

2) I saw several issues where users did something like: 
```
NCHRS=diploid_chromosomes number
haphic pipeline purged_haps_combined.fa HiC.filtered.bam $NCHRS --gfa "${GFA1},${GFA2}" --correct_nrounds 2 --remove_allelic_links 2 --threads 48 --processes 48
```

So they combine the two haplotigs that we get back from hifiasm?! My approach would have been to run:
```
NCHRS=haploid_chromosomes number
haphic pipeline species.hic.hap1.p_ctg.fasta HiC.filtered.bam haploid_chromosomes number --gfa "species.hic.hap1.p_ctg.gfa, species.hic.hap1.p_ctg.gfa" --correct_nrounds 2 --remove_allelic_links 2 --threads 48 --processes 48
```

And then I would repeat this for the second haplotig. 

```
NCHRS=haploid_chromosomes number
haphic pipeline species.hic.hap2.p_ctg.fasta HiC.filtered.bam haploid_chromosomes number --gfa "species.hic.hap1.p_ctg.gfa, species.hic.hap1.p_ctg.gfa" --correct_nrounds 2 --remove_allelic_links 2 --threads 48 --processes 48
```

Is that wrong? Do I need to combine them? How would I do this?

**Comment by zengxiaofei** [comment]
Hi @AlcaArctica,

Thank you for using HapHiC.

The first question
> I have learned from the issues, that you do not recommend to use purge_dups. So my new approach should probably be hifiasm+hic -> haphic --> juicer. Is that correct?

I have updated my understanding of purge_dups in [an issue](https://github.com/zengxiaofei/HapHiC/issues/64#issuecomment-2359903425):

> In trio mode, hifiasm sets `-l` to `0` by default, which aligns with my previous understanding. However, in Hi-C mode, hifiasm sets `-l` to `3` by default. This may be due to a different algorithm used in Hi-C-based phasing. In this mode, hifiasm relies on determining homologous coverage and a similarity threshold to identify haplotigs. Therefore, we can understand why the authors recommend tuning the `--hom-cov` and `-s` parameters in such scenarios.

The built-in purge_dups function in hifiasm should be left as its default settings. However, I still do not recommend running a stand-alone purge_dups process. This is because, when assembling a haplotype-resolved assembly, we always want to assemble the heterozygous regions in both haplotypes rather than remove one set of them. Even though there could be some phasing errors in hifiasm assemblies that usually result in unbalanced haplotypes, we can still correct the assemblies using tools like Juicebox or by tuning the `--hom-cov` and `-s` parameters. If we run an stand-alone pruge_dups, some heterozygous regions may be removed, leading to incomplete haplotypes.

The second question:
> Is that wrong? Do I need to combine them? How would I do this?

There are indeed two strategies for scaffolding haplotype-resolved assemblies. Some users concatenate haplotypes into a single FASTA file for Hi-C data mapping and scaffolding. I would recommend this strategy as a priority, as aligners can find an optimal alignment for each Hi-C read. However, this strategy works well only when the heterozygosity level is high enough since there should be enough Hi-C links after MAPQ>=1 filtering. If the effective Hi-C links after filtering are not sufficient to run HapHiC or manually curate in Juicebox, you can scaffold each haplotype separately, just as you would with your regular strategy. This strategy will map Hi-C data from both haplotypes into a single haplotype. Many more Hi-C links will be retained, but nearly half of them are actually incorrect mappings, which can cause issues when there are structural variations between the two haplotypes. However, if the heterozygosity level is too low, there's no alternative but to accept this compromise.

Best regards,
Xiaofei

**Comment by AlcaArctica** [comment]
Thank you for this informative reply! I am still struggling with the second part a bit though. Let's say my heterozygosity levels are high enough and I want to follow your recommended approach. I would do something like:
```
NCHRS=diploid_chromosomes number
haphic pipeline hap1_hap2_combined.fa HiC.filtered.bam $NCHRS --gfa "hic.hap1.p_ctg.gfa,hic.hap1.p_ctg.gfa" --correct_nrounds 2 --remove_allelic_links 2 --threads 48 --processes 48
```

But I don't understand what my result would be in this case and how I would arrive at a haplotype-resolved assembly? As in this case I input the combined contigs from hap1 and hap2 as defined by hifiasm. However, the resulting scaffolded assembly that will be generated by HapHiC cannot be attributed to hap1 or hap2.

**Comment by zengxiaofei** [comment]
First, it's important to clarify that whether using hifiasm or HapHiC, if we are employing Hi-C data for haplotype phasing, we cannot achieve whole-genome level phasing but can only reach chromosome-level phasing (to achieve the former, trio data from parents would be needed). This means that hifiasm places contigs from the same chromosome haplotype into a single GFA file, but contigs between different chromosomes may not come from the same parent. For chromosome scaffolding, similarly, we only need to cluster contigs of the same chromosome haplotype together and determine the order and orientation of contigs within the chromosome to achieve chromosome-level phasing. HapHiC does not directly infer which chromosomes are a pair of homologous chromosomes and output them as two separate files. This is because scaffolding can still be prone to errors, and users can easily adjust in Juicebox and determine which chromosomes are a pair of homologous chromosomes through these three methods (it should be emphasized again that as long as homologous chromosomes can be distinguished without knowing the combinations between non-homologous chromosomes, it is considered chromosome-level phasing):

* Homologous chromosomes often exhibit diagonally distributed Hi-C signals on Hi-C heatmaps, which are usually caused by switch errors and mapping errors introduced during genome assembly.
* Self-alignment. Due to the small sequence differences between homologous chromosomes, their corresponding relationship can be found through * * Alignment to a monoploid reference genome.

We recommend concatenating the two haplotypes and then aligning the Hi-C reads to both haplotypes simultaneously. This approach allows the read mapper to find the best alignment for each pair of Hi-C reads (although many will be filtered out with MAPQ>=1 due to multiple alignments). Additionally, the phasing results from hifiasm are not always correct, especially in highly heterozygous regions where hifiasm might tend to place these heterozygous regions into a single haplotype, leading to imbalanced haplotypes. In such cases, HapHiC may be able to correct these errors. Of course, if you believe that the phasing results from hifiasm are already sufficiently accurate and wish to fully trust the HapHiC results, you can add the `--gfa` parameter. HapHiC will ensure that contigs from different GFA files will not be clustered together. 

Finally, I would like to remind you that if you plan to scaffold each haplotype separately, only the GFA file corresponding to that haplotype should be specified.

Summary of parameters related to `--gfa`:

* HapHiC utilizes read depth information from GFA files to identify potential collapsed contigs (always enabled).
* If only a single GFA file is provided, HapHiC will solely identify potential collapsed contigs.
* If multiple GFA files are provided, HapHiC assumes they are phased GFA files. The default parameter (`--phasing_weight 1`) ensures that contigs from different GFA files will not be clustered together.
* The --phasing_weight parameter can be adjusted to modify the degree to which HapHiC trusts the phasing results from hifiasm.
* Please ensure consistency between the input FASTA file and GFA file(s).

**Comment by AlcaArctica** [comment]
Thank you so much for going through the trouble of explaining this in so much detail. I have a much better understanding of the process now and know what I need to go ahead! Kudos to you.

**Comment by zengxiaofei** [comment]
Hi @pjm43,

A common assumption is that the two haplotypes should be of similar length. If the default hifiasm output shows a significant size difference between hap1 and hap2, it's recommended to adjust the -s parameter (typically by lowering its value) to ensure they meet expectations.

Best,
Xiaofei

**Comment by zengxiaofei** [comment]
From the heatmap you provided, I can observe some abnormal signals between homologous chromosomes, which typically indicate assembly errors. Due to the low resolution of the image, I can't determine whether these are chimeric contigs or collapsed contigs. However, since you've already run haphic with `--correct_nrounds 2`, I suspect they might be the latter (collapsed contigs). If correct, this suggests a generally highly heterozygous genome with discrete low-heterozygosity regions.

Currently, there are no very effective methods for handling collapsed contigs during the scaffolding process - this is a limitation of using unitigs for scaffolding. For very long collapsed contigs, we usually manually copy them, but in your assembly these appear to be quite short, making manual intervention impractical.

My recommendation would still be to try assembling in Hi-C mode (using `hap*.p_ctg`) with lower `-s`. If hifiasm can properly phase the two haplotypes, you should see significant improvements in contig contiguity and reduction in collapsed regions.

Xiaofei
